# Generated by Django 5.0.6 on 2024-06-10 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
